/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package nhom.demo.Form.MainBoard;

import javax.swing.ImageIcon;
import nhom.demo.Form.MainBoard.QuanLySinhVien.QuanLySinhVienForm;

import java.awt.*;
import javax.swing.JTabbedPane;
import nhom.demo.Form.MainBoard.QuanLyHocPhi.QuanLyHocPhiForm;

import nhom.demo.Form.MainBoard.QuanLySinhVien.QuanLySinhVienFormChinhSua;
import nhom.demo.Form.MainBoard.QuanLySinhVien.QuanLySinhVienFormThemMoi;
import nhom.demo.Form.MainBoard.XuatFileExcel.XuatFileExcel;

/**
 *
 * @author hlade
 */
public class MainBoardForm extends javax.swing.JFrame {
    
    private QuanLySinhVienForm qlsvf;
    QuanLyHocPhiForm quanLyHocPhiForm;
    QuanLySinhVienFormThemMoi quanLySinhVienFormThemMoi;
    QuanLySinhVienFormChinhSua quanLySinhVienFormChinhSua;
    XuatFileExcel xfe;

    /**
     * Creates new form MainBoardForm
     */
    public MainBoardForm() {
        initComponents();
           setLocationRelativeTo(null);
           setVisible( true );
           setDefaultCloseOperation( EXIT_ON_CLOSE );
           setSize(800, 768);
            Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
            this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem5 = new javax.swing.JMenuItem();
        jToolBar1 = new javax.swing.JToolBar();
        btnDangXuat = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btnQLHocPhi = new javax.swing.JButton();
        btnQLSinhVien = new javax.swing.JToggleButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        btnGioiThieu = new javax.swing.JButton();
        tpnMain = new javax.swing.JTabbedPane();
        mainBoardMenu = new javax.swing.JMenuBar();
        mnuItemHeThong = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        MnuItemQuanLy = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        mnuItemCongCu = new javax.swing.JMenu();
        xuatFileExcel = new javax.swing.JMenuItem();
        mnuGioiThieu = new javax.swing.JMenu();

        jMenuItem5.setText("jMenuItem5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        btnDangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nhom/demo/icons/logout-icon-32.png"))); // NOI18N
        btnDangXuat.setText("Đăng xuất");
        btnDangXuat.setFocusable(false);
        btnDangXuat.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDangXuat.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangXuatActionPerformed(evt);
            }
        });
        jToolBar1.add(btnDangXuat);

        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton2);
        jToolBar1.add(jSeparator1);

        btnQLHocPhi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nhom/demo/icons/Login-icon-32.png"))); // NOI18N
        btnQLHocPhi.setText("Quản Lý Học Phí");
        btnQLHocPhi.setFocusable(false);
        btnQLHocPhi.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnQLHocPhi.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnQLHocPhi);

        btnQLSinhVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nhom/demo/icons/10207-man-student-light-skin-tone-icon-32.png"))); // NOI18N
        btnQLSinhVien.setText("Quản Lý Sinh Viên");
        btnQLSinhVien.setFocusable(false);
        btnQLSinhVien.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnQLSinhVien.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnQLSinhVien);
        jToolBar1.add(jSeparator2);

        btnGioiThieu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nhom/demo/icons/Actions-help-about-icon-32.png"))); // NOI18N
        btnGioiThieu.setText("Giới Thiệu");
        btnGioiThieu.setFocusable(false);
        btnGioiThieu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGioiThieu.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnGioiThieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGioiThieuActionPerformed(evt);
            }
        });
        jToolBar1.add(btnGioiThieu);

        mnuItemHeThong.setText("Hệ Thống");
        mnuItemHeThong.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, 0));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nhom/demo/icons/logout-icon-16.png"))); // NOI18N
        jMenuItem1.setText("Đăng Xuất");
        mnuItemHeThong.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, 0));
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nhom/demo/icons/Button-Close-icon-16.png"))); // NOI18N
        jMenuItem2.setText("Thoát");
        mnuItemHeThong.add(jMenuItem2);

        mainBoardMenu.add(mnuItemHeThong);

        MnuItemQuanLy.setText("Quản Lý");
        MnuItemQuanLy.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nhom/demo/icons/10207-man-student-light-skin-tone-icon-16.png"))); // NOI18N
        jMenuItem3.setText("Quản Lý Sinh Viên");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        MnuItemQuanLy.add(jMenuItem3);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nhom/demo/icons/Actions-document-edit-icon-16.png"))); // NOI18N
        jMenuItem4.setText("Quản Lý Tín Chỉ");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        MnuItemQuanLy.add(jMenuItem4);

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nhom/demo/icons/Actions-edit-delete-icon-16.png"))); // NOI18N
        jMenuItem6.setText("Quản Lý Học Phí");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        MnuItemQuanLy.add(jMenuItem6);

        mainBoardMenu.add(MnuItemQuanLy);

        mnuItemCongCu.setText("Công Cụ");
        mnuItemCongCu.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N

        xuatFileExcel.setText("Xu?t file excel");
        xuatFileExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xuatFileExcelActionPerformed(evt);
            }
        });
        mnuItemCongCu.add(xuatFileExcel);

        mainBoardMenu.add(mnuItemCongCu);

        mnuGioiThieu.setText("Giới Thiệu");
        mnuGioiThieu.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        mainBoardMenu.add(mnuGioiThieu);

        setJMenuBar(mainBoardMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 421, Short.MAX_VALUE)
            .addComponent(tpnMain, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tpnMain, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void hienThiQLSV() {
        if(qlsvf == null)
        {
            qlsvf = new QuanLySinhVienForm();
            ImageIcon icon = new ImageIcon(getClass()
                    .getResource("/nhom/demo/icons/10207-man-student-light-skin-tone-icon-64.png"));
            tpnMain.addTab("Quan Ly Sinh Vien", icon, qlsvf, "Quan Ly Sinh Vien");
            tpnMain.setSelectedComponent(qlsvf);
        }
    }
    
    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        hienThiQLSV();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        showQlyHocPhi();
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void btnDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangXuatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDangXuatActionPerformed

    private void btnGioiThieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGioiThieuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGioiThieuActionPerformed

    private void xuatFileExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xuatFileExcelActionPerformed
        // TODO add your handling code here:
        this.showFormXuatFile();
        
    }//GEN-LAST:event_xuatFileExcelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainBoardForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainBoardForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainBoardForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainBoardForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainBoardForm().setVisible(true);
            }
        });
    }
    
    public JTabbedPane getTpnMain()
    {
        return tpnMain;
    }
    
    public void hienThiFormThemMoiSV() {                                           
        // TODO add your handling code here:
         if(quanLySinhVienFormThemMoi == null)
        {

            quanLySinhVienFormThemMoi = new QuanLySinhVienFormThemMoi();
            ImageIcon icon = new ImageIcon(getClass()
                    .getResource("/nhom/demo/icons/10207-man-student-light-skin-tone-icon-64.png"));
  
            tpnMain.addTab("Quan Ly Sinh Vien", icon, quanLySinhVienFormThemMoi, "Quan Ly Sinh Vien");
            tpnMain.setSelectedComponent(quanLySinhVienFormThemMoi);

        }
    }

    public void showQlyHocPhi() {                                           
        // TODO add your handling code here:
         if(quanLyHocPhiForm == null)
        {

            quanLyHocPhiForm = new QuanLyHocPhiForm();
            ImageIcon icon = new ImageIcon(getClass()
                    .getResource("/nhom/demo/icons/10207-man-student-light-skin-tone-icon-64.png"));
  
            tpnMain.addTab("Quan Ly Hoc Phi", icon, quanLyHocPhiForm, "Quan Ly Hoc Phi");
            tpnMain.setSelectedComponent(quanLyHocPhiForm);

        }
    }

    public void showEditForm(String maSV) {
        if(quanLySinhVienFormChinhSua == null)
        {
            quanLySinhVienFormChinhSua = new QuanLySinhVienFormChinhSua(maSV);
            ImageIcon icon = new ImageIcon(getClass()
                    .getResource("/nhom/demo/icons/10207-man-student-light-skin-tone-icon-64.png"));

            tpnMain.addTab("Quan Ly Sinh Vien", icon, quanLySinhVienFormChinhSua, "Quan Ly Sinh Vien");
            tpnMain.setSelectedComponent(quanLySinhVienFormChinhSua);
        }
    }
    
    public void showFormXuatFile() {
        if(xfe == null)
        {
            xfe = new XuatFileExcel();
            ImageIcon icon = new ImageIcon(getClass()
                    .getResource("/nhom/demo/icons/10207-man-student-light-skin-tone-icon-64.png"));

            tpnMain.addTab("Quan Ly Xuat File", icon, xfe, "Quan Ly Sinh Vien");
            tpnMain.setSelectedComponent(xfe);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MnuItemQuanLy;
    private javax.swing.JButton btnDangXuat;
    private javax.swing.JButton btnGioiThieu;
    private javax.swing.JButton btnQLHocPhi;
    private javax.swing.JToggleButton btnQLSinhVien;
    private javax.swing.JButton jButton2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenuBar mainBoardMenu;
    private javax.swing.JMenu mnuGioiThieu;
    private javax.swing.JMenu mnuItemCongCu;
    private javax.swing.JMenu mnuItemHeThong;
    private javax.swing.JTabbedPane tpnMain;
    private javax.swing.JMenuItem xuatFileExcel;
    // End of variables declaration//GEN-END:variables
}
