/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package nhom.demo.Form.MainBoard.QuanLySinhVien;

import nhom.demo.Form.MainBoard.MainBoardForm;
import nhom.demo.Model.SinhVien;
import nhom.demo.Repo.SinhVienRepository;

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.util.ArrayList;
import java.util.List;
import java.util.function.Consumer;

/**
 *
 * @author hlade
 */
public class QuanLySinhVienForm extends javax.swing.JPanel {
    QuanLySinhVienFormThemMoi quanLySinhVienFormThemMoi;
    List<SinhVien> list = SinhVienRepository.readData();

    /**
     * Creates new form QuanLySinhVienForm
     */
    public QuanLySinhVienForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtName = new javax.swing.JTextField();
        txtClass = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnSearch = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jLabel1.setText("Họ Tên :");

        jLabel2.setText("Lớp :");

        btnSearch.setText("Tìm Kiếm");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnAdd.setText("Thêm");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        jButton3.setText("Nhập Lại");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        int n = list.size();
        Object[][] data = new Object[n][6];
        for (int i= 0;i < n;i++)
        {

            for (int j = 0;j<6;j++)
            {
                if(j == 0)
                {
                    data[i][j] = list.get(i).getMaSv();
                }
                if(j == 1)
                {
                    data[i][j] = list.get(i).getHoTen();
                }
                if(j == 2)
                {
                    data[i][j] = list.get(i).getGioiTinh();
                }
                if(j == 3)
                {
                    data[i][j] = list.get(i).getDiaChi();
                }
                if(j == 4)
                {
                    data[i][j] = list.get(i).getLop();
                }
                if(j == 5)
                {
                    data[i][j] = list.get(i).getNganh();
                }
            }
        }

        //jButton3.setText("Nhập lại");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(data,
                new String [] {
                        "MaSV", "Họ Tên", "Giới Tính", "Địa Chỉ", "Lớp", "Ngành",
                }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtClass, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(215, 215, 215)
                        .addComponent(btnSearch)
                        .addGap(18, 18, 18)
                        .addComponent(btnAdd)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)))
                .addGap(40, 40, 40))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtClass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSearch)
                    .addComponent(btnAdd)
                    .addComponent(jButton3))
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
       (new MainBoardForm()).test();
    }//GEN-LAST:event_btnAddActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt){
        txtClass.setText("");
        txtName.setText("");
    }
    
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        JTable source = (JTable)evt.getSource();
        int row = source.rowAtPoint( evt.getPoint() );

        String s=source.getModel().getValueAt(row,0)+"";
        System.out.println(s);
        
        SinhVien sinhVien = new SinhVien();
        for (SinhVien sinhVien1 : list) {
            System.out.println("123");
            if(sinhVien1.getMaSv().equals(s)) sinhVien = sinhVien1;
        }
        System.out.println(sinhVien.getMaSv());
        

        (new MainBoardForm()).showEditForm();
    }//GEN-LAST:event_jTable1MouseClicked
    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {
        if(!txtName.getText().isEmpty())
        {
            list.forEach(new Consumer<SinhVien>()
            {
                List<SinhVien> result = new ArrayList<>();
                @Override
                public void accept(SinhVien sinhVien) {
                    if(sinhVien.getHoTen().contains(txtName.getText()))
                        result.add(sinhVien);
                    int n = result.size();

                    Object[][] data = new Object[n][5];
                    for (int i= 0;i < n;i++)
                    {

                        for (int j = 0;j<6;j++)
                        {
                            if(j == 0)
                            {
                                data[i][j] = list.get(i).getMaSv();
                            }
                            if(j == 1)
                            {
                                data[i][j] = list.get(i).getHoTen();
                            }
                            if(j == 2)
                            {
                                data[i][j] = list.get(i).getGioiTinh();
                            }
                            if(j == 3)
                            {
                                data[i][j] = list.get(i).getDiaChi();
                            }
                            if(j == 4)
                            {
                                data[i][j] = list.get(i).getLop();
                            }
                            if(j == 5)
                            {
                                data[i][j] = list.get(i).getNganh();
                            }
                        }
                    }
                    jTable1.setModel(new javax.swing.table.DefaultTableModel(data,
                            new String [] {
                                    "MaSV", "Ho Ten", "Gioi Tinh", "Dia Chi", "Lop", "Nganh",
                            }
                    ));
                    jScrollPane1.setViewportView(jTable1);
                }
            });
            return;
        }
        if(!txtClass.getText().isEmpty())
        {
            list.forEach(new Consumer<SinhVien>()
            {
                List<SinhVien> result = new ArrayList<>();
                @Override
                public void accept(SinhVien sinhVien) {
                    if(sinhVien.getLop().contains(txtClass.getText()))
                        result.add(sinhVien);
                    int n = result.size();

                    Object[][] data = new Object[n][5];
                    for (int i= 0;i < n;i++)
                    {

                        for (int j = 0;j<6;j++)
                        {
                            if(j == 0)
                            {
                                data[i][j] = list.get(i).getMaSv();
                            }
                            if(j == 1)
                            {
                                data[i][j] = list.get(i).getHoTen();
                            }
                            if(j == 2)
                            {
                                data[i][j] = list.get(i).getGioiTinh();
                            }
                            if(j == 3)
                            {
                                data[i][j] = list.get(i).getDiaChi();
                            }
                            if(j == 4)
                            {
                                data[i][j] = list.get(i).getLop();
                            }
                            if(j == 5)
                            {
                                data[i][j] = list.get(i).getNganh();
                            }
                        }
                    }
                    jTable1.setModel(new javax.swing.table.DefaultTableModel(data,
                            new String [] {
                                    "MaSV", "Ho Ten", "Gioi Tinh", "Dia Chi", "Lop", "Nganh",
                            }
                    ));
                    jScrollPane1.setViewportView(jTable1);

                }
            });
            return;
        }
        if(!txtName.getText().isEmpty() && !txtClass.getText().isEmpty())
        {
            list.forEach(new Consumer<SinhVien>()
            {
                List<SinhVien> result = new ArrayList<>();
                @Override
                public void accept(SinhVien sinhVien) {
                    if(sinhVien.getHoTen().contains(txtName.getText()) && sinhVien.getLop().contains(txtClass.getText()))
                        result.add(sinhVien);
                    int n = result.size();

                    Object[][] data = new Object[n][5];
                    for (int i= 0;i < n;i++)
                    {

                        for (int j = 0;j<6;j++)
                        {
                            if(j == 0)
                            {
                                data[i][j] = list.get(i).getMaSv();
                            }
                            if(j == 1)
                            {
                                data[i][j] = list.get(i).getHoTen();
                            }
                            if(j == 2)
                            {
                                data[i][j] = list.get(i).getGioiTinh();
                            }
                            if(j == 3)
                            {
                                data[i][j] = list.get(i).getDiaChi();
                            }
                            if(j == 4)
                            {
                                data[i][j] = list.get(i).getLop();
                            }
                            if(j == 5)
                            {
                                data[i][j] = list.get(i).getNganh();
                            }
                        }
                    }
                    jTable1.setModel(new javax.swing.table.DefaultTableModel(data,
                            new String [] {
                                    "MaSV", "Ho Ten", "Gioi Tinh", "Dia Chi", "Lop", "Nganh",
                            }
                    ));
                    jScrollPane1.setViewportView(jTable1);
                }
            });
            return;
        }
        int n = list.size();
        Object[][] data = new Object[n][5];
        for (int i= 0;i < n;i++)
        {

            for (int j = 0;j<6;j++)
            {
                if(j == 0)
                {
                    data[i][j] = list.get(i).getMaSv();
                }
                if(j == 1)
                {
                    data[i][j] = list.get(i).getHoTen();
                }
                if(j == 2)
                {
                    data[i][j] = list.get(i).getGioiTinh();
                }
                if(j == 3)
                {
                    data[i][j] = list.get(i).getDiaChi();
                }
                if(j == 4)
                {
                    data[i][j] = list.get(i).getLop();
                }
                if(j == 5)
                {
                    data[i][j] = list.get(i).getNganh();
                }
            }
        }

        jButton3.setText("Nh?p l?i");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(data,
                new String [] {
                        "MaSV", "Ho Ten", "Gioi Tinh", "Dia Chi", "Lop", "Nganh",
                }
        ));
        jScrollPane1.setViewportView(jTable1);
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtClass;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
