/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package nhom.demo.Form.MainBoard.QuanLyTinChi;

import java.util.ArrayList;
import java.util.List;
import nhom.demo.Model.LK_SinhVien_MonHoc;
import nhom.demo.Model.MonHoc;
import nhom.demo.Model.SinhVien;
import nhom.demo.Repo.SinhVienRepository;

/**
 *
 * @author hlade
 */
public class QuanLyTinChiForm extends javax.swing.JPanel {
    List<SinhVien> list = SinhVienRepository.readData();
    List<LK_SinhVien_MonHoc> listLK = new ArrayList<>();
    String maSVSelected = "";

    private void showTable() {
        
        
        for (SinhVien sinhVien : list) {
            LK_SinhVien_MonHoc lK_SinhVien_MonHoc = new LK_SinhVien_MonHoc();
            
            lK_SinhVien_MonHoc.setDsachMon();
            listLK.add(lK_SinhVien_MonHoc);
            
        }
        int n = listLK.size();
        System.out.println(n);
        Object[][] data = new Object[n][4];
        for (int i= 0;i < n;i++)
        {

            for (int j = 0;j<4;j++)
            {
                if(j == 0)
                {
                    data[i][j] = listLK.get(i).getSv().getMaSv();
                }
                if(j == 1)
                {
                    data[i][j] = listLK.get(i).getSv().getHoTen();
                }
                if(j == 2)
                {
                    String monHocS = "";
                    for (MonHoc monHoc : listLK.get(i).getDsachMon()) {
                        monHocS += "\n" + monHoc.getTenMonHoc();
                    }
                    data[i][j] = monHocS;
                }
                if(j == 3)
                {
                   long tongSoTin = 0;
                    for (MonHoc monHoc : listLK.get(i).getDsachMon()) {
                        tongSoTin += monHoc.getSoTin();
                    }
                    data[i][j] = tongSoTin;
                }
              
            }
        }

        jTable1.setModel(new javax.swing.table.DefaultTableModel(data,
                new String [] {
                        "MaSV", "Họ Tên", "Các Môn Hoc","Tong So Tin Chi",
                }
        ));
        jScrollPane1.setViewportView(jTable1);
    }
    /**
     * Creates new form QuanLyTinChiForm
     */
    public QuanLyTinChiForm() {
        initComponents();
        showTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txtName = new javax.swing.JTextField();
        txtClass = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnSearch = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("Họ Tên :");

        jLabel2.setText("Lớp :");

        btnSearch.setText("Tìm Kiếm");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        jButton3.setText("Nhập Lại");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(259, Short.MAX_VALUE)
                .addComponent(btnSearch)
                .addGap(44, 44, 44)
                .addComponent(jButton3)
                .addGap(320, 320, 320))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(0, 12, Short.MAX_VALUE)
                            .addComponent(jLabel1)
                            .addGap(18, 18, 18)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(72, 72, 72)
                            .addComponent(jLabel2)
                            .addGap(18, 18, 18)
                            .addComponent(txtClass, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(34, 34, 34)))
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(btnSearch))
                .addContainerGap(254, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtClass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2))
                    .addGap(87, 87, 87)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(26, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // get maSV selected
        int row = jTable1.getSelectedRow();
        maSVSelected = jTable1.getValueAt(row, 0).toString();

        //        JTable source = (JTable)evt.getSource();
        //        int row = source.rowAtPoint( evt.getPoint() );
        //
        //        String s=source.getModel().getValueAt(row,0)+"";
        //        System.out.println(s);
        //
        //        SinhVien sinhVien = new SinhVien();
        //        for (SinhVien sinhVien1 : list) {
            //            System.out.println("123");
            //            if(sinhVien1.getMaSv().equals(s)) sinhVien = sinhVien1;
            //        }
        //        System.out.println(sinhVien.getMaSv());
        //
        //
        //        (new MainBoardForm()).showEditForm();
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtClass;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
