/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nhom.demo.Form.MainBoard.QuanLyHocPhi;

import static com.sun.tools.attach.VirtualMachine.list;
import static java.util.Collections.list;
import java.util.List;

import javax.swing.JOptionPane;
import javax.swing.JTable;
import nhom.demo.Form.MainBoard.MainBoardForm;
import nhom.demo.Model.LK_SinhVien_MonHoc;
import nhom.demo.Model.SinhVien;
import nhom.demo.Repo.SinhVienRepository;

/**
 *
 * @author hieuv
 */
public class QuanLyHocPhiForm extends javax.swing.JPanel {
    List<SinhVien> list = SinhVienRepository.readData();
    public static final int TIEN_MOI_TIN = 350;
    String maSVSelected = "";

    private void showTable() {
         int n = list.size();
        Object[][] data = new Object[n][5];
        for (int i= 0;i < n;i++)
        {

            for (int j = 0;j<6;j++)
            {
                if(j == 0)
                {
                    data[i][j] = list.get(i).getMaSv();
                }
                else if(j == 1)
                {
                    data[i][j] = list.get(i).getHoTen();
                }
                else if(j == 2)
                {
                    data[i][j] = list.get(i).getLop();
                }
                else if(j == 3)
                {
                    data[i][j] = list.get(i).getSoTienTrongTK();
                }
                else if(j == 4)
                {
                    data[i][j] = list.get(i).getSoTinChiDk() * TIEN_MOI_TIN;
                }
            }
        }

        jTable1.setModel(new javax.swing.table.DefaultTableModel(data,
                new String [] {
                        "MaSV", "Họ Tên", "Lớp", "Số tiền trong tk", "Số tiền nợ"
                }
        ));
        jScrollPane1.setViewportView(jTable1);

    }

    /**
     * Creates new form QuanLyHocPhiForm
     */
    public QuanLyHocPhiForm() {
        initComponents();
        showTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txtName = new javax.swing.JTextField();
        txtClass = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnSearch = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(798, 376));

        jButton3.setText("Nhập Lại");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("Họ Tên :");

        jLabel2.setText("Lớp :");

        btnSearch.setText("Tìm Kiếm");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        jButton1.setText("Thanh toan");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 36, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtClass, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(309, 309, 309)
                        .addComponent(btnSearch)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(40, 40, 40))
            .addGroup(layout.createSequentialGroup()
                .addGap(350, 350, 350)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtClass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSearch)
                    .addComponent(jButton3))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(57, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // get maSV selected
        int row = jTable1.getSelectedRow();
        maSVSelected = jTable1.getValueAt(row, 0).toString();
              
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // check if maSV selected
        if (maSVSelected.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Chọn sinh viên cần thanh toán!");
            return;
        }

        // confirm thanh toan
        int confirm = JOptionPane.showConfirmDialog(this, "Thanh toán ngay?");
        if (confirm == JOptionPane.NO_OPTION) {
            return;
        }

        for (SinhVien sinhVien : list) {
            if (maSVSelected.equals(sinhVien.getMaSv())) {
                LK_SinhVien_MonHoc lk = new LK_SinhVien_MonHoc();
                lk.setSv(sinhVien);

                boolean thanhToan = lk.thanhToan();

                if (thanhToan) {
                    JOptionPane.showMessageDialog(this, "Thanh toán thành công!");
                } else {
                    JOptionPane.showMessageDialog(this, "Thanh toán thất bại! (kiểm tra lại tiền trong tài khoản)");
                }

                break;
            }
        }
        
        showTable();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtClass;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
